releases:
  - name: browser-node3
    namespace: browser
    chart: ../chart
    version: 2.8.0
    values:
      - ./values-node3-browser.yaml

  - name: browser-node4
    namespace: browser
    chart: ../chart
    version: 2.8.0
    values:
      - ./values-node4-browser.yaml

#  - name: browser-business
#    namespace: browser
#    chart: ../chart
#    version: 2.8.0
#    values:
#      - ./values-browser-business.yaml
#    needs:
#      - browser-postgresql
#
#  - name: browser-postgresql
#    namespace: browser
#    chart: ../chart
#    version: 16.0.1
#    values:
#      - ./values-postgresql.yaml