#nameOverride: postgre

#imagePullSecrets: []
defaultImage: hamsaprivacyacrdev.azurecr.io/postgres
defaultImageTag: latest
defaultImagePullPolicy: "Always"

envs:
    POSTGRES_USER: hamsa-dev
    POSTGRES_PASSWORD: dev123

services:
  postgresql:
    type: LoadBalancer
    ports:
      - port: 5432
        protocol: TCP

statefulSets:
  "" :
    replicas: 1
    containers:
      - name: postgresql
        args: [ "-c", "max_connections=500" ]
        command:
          - /bin/sh
          - -c
          - |
            mkdir -p /data/db/pgdata/data
            chown -R postgres:postgres /data/db/pgdata/data
            chmod -R 750 /data/db/pgdata/data
            exec docker-entrypoint.sh postgres
        env:
          - name: PGDATA
            value: /data/db/pgdata/data
        volumeMounts:
          - name: postgre-data
            mountPath: /data/db/pgdata
          - name: init-sql-vol
            mountPath: /docker-entrypoint-initdb.d
        envFrom:
          - configMapRef:
              name: browser-postgresql-envs
              optional: false

    #   imagePullSecret: "ucl-secret"
    volumes:
      - name: init-sql-vol
        type: configMap
        originalName: postgresql-init-sql

    nodeSelector:
      purpose: "browser"

    volumeClaimTemplates:
      - metadata:
          name: postgre-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "managed-csi"
          resources:
            requests:
              storage: 40Gi

    configMaps:
      init-sql:
        data:
          init.sql: |
            CREATE DATABASE transaction;