
#nameOverride: browser

imagePullSecrets: {}
defaultImage: hamsaprivacyacrdev.azurecr.io/hamsa-msft-browser
defaultImageTag: 0.0.8
defaultImagePullPolicy: "Always"

envs:
  API_URL: http://qa-node3-node.hamsa-ucl.com:8123
  VERIFY_CONTRACT_ADDRESS: 0xcd1E859D886fDf2C05CEB4D8240262FaFd6C6b7F
  QUERY_NODE: http://54.193.75.6:8545
  USERS: '[{"email":"admin@node3.com","address":"0xe46Fe251dd1d9FfC247bc0DDb6D61e4EE4416ecB","privateKey":"555332672ce947d150d23a36bf3847078291f89bda7073829bb718c77d626787","password":"Test@123","role":"admin"},{"email":"user@node3.com","address":"0x786ff0e4ccB190C039940955a1E50a7681538Edb","privateKey":"ee9cc2c60beca5d9e38747a065d0c7d5dccf9d2f189850756444ef06b856f932","password":"Test@123","role":"normal"}]'

services:
  "web":
    type: LoadBalancer
    ports:
      - port: 8080
        protocol: TCP

    annotations:
      external-dns.alpha.kubernetes.io/hostname: qa-browser3.hamsa-ucl.com
      external-dns.alpha.kubernetes.io/ttl: "3000"

statefulSets:
  "" :
    replicas: 1
    containers:
      - name: app
        envFrom:
          - configMapRef:
              name: browser-node3-envs
              optional: false

        preemptionPolicy: Never
        resources:
          requests:
            memory: "1Gi"

        volumeMounts:
          - name:  nginx-url
            mountPath: /usr/share/nginx/html2

        ports:
          - containerPort: 8080
            name: web
            protocol: TCP

    volumes:
      - name: nginx-url
        type: configMap
        originalName: browser-node3-nginx-url


    nodeSelector:
      purpose: "other"
    imagePullSecret: "ucl-secret"


#configMaps:
#  nginx-url:
#    data:
#      url.txt: |
#        http://qa-node3-node.hamsa-ucl.com:8123,0x552c8Cd1E07fb790d9f78f2cf4337aEFe21587a8
