nameOverride: node4-msft-executor

imagePullSecrets: {}
defaultImage: hamsaprivacyacrdev.azurecr.io/hamsa-msft-executor
defaultImageTag: 0.0.5
defaultImagePullPolicy: "Always"

envs:
  NODEDB_URL: node4-postgre-postgresql:5432
  DVP_L1URL: http://172.191.120.239:8545
  DVP_L1MATCHSUBMITTERKEYS: 360b3f569579a0e824fab18c21d6e583b060e2339142c6833c899029fc8e428d,f951e1bd9ef0359e6886ae77e5fd30d566ef098d099c78fd3fb68588657618cc
  DVP_L1MATCHSCADDRESS: 0x8E8986A2940af870b7a0F44a053C1cEcCA3D1053

services: 
  "api":
    ports:
    - port: 50081
      protocol: TCP

statefulSets:
  "" :
    replicas: 1
    containers:
      - name: app
        envFrom:
          - configMapRef:
              name: node4-msft-executor-config
              optional: true
          - configMapRef:
              name: node4-msft-executor-envs
              optional: true
          - configMapRef:
              name: node4-msft-executor-secrets
              optional: true
        command:
          - "/bin/sh"
          - "-c"
          - "/app/hamsa-msft-executor_main run --cfg /app/executor.config.toml --custom-network-file /app/genesis.config.json"
        ports:
          - containerPort: 50081
            name: executor-api
            protocol: TCP
        volumeMounts:
          - name: app-data
            mountPath: /app/db/executor-db
    imagePullSecret: "acr-secret"
    nodeSelector:
      purpose: "other"
    volumeClaimTemplates:
      - metadata:
          name: app-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "managed-csi"
          resources:
            requests:
              storage: 40Gi
